#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect specific nginx configurations
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
# it must return a page that contains the string Hello World!
# You can’t use systemctl for restarting nginx

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
