#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 251616-web-01 35.175.63.220 check
   server 251616-web-02 184.73.152.59 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
