#!/usr/bin/env bash
# Configures HAproxy so that it send traffic to web-01 and web-02

# Update package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Backup the original HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Create a new HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend web
    bind *:80
    mode http
    default_backend servers

backend servers
    mode http
    balance roundrobin
    server 251616-web-01 35.175.63.220 check
    server 251616-web-02 184.73.152.59 check
EOL

# Restart HAProxy
sudo service haproxy restart

# Enable HAProxy to start on boot
sudo systemctl enable haproxy
