#!/usr/bin/env bash
# A bash script that displays To infinity and beyond indefinitely.
# Prints I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

i=1
while [ "$i" -eq 1 ]; do
	echo "To infinity and beyond"
	sleep 2
done
