#!/usr/bin/env bash
# This script that displays the content of the file /etc/passwd.

filename="/etc/passwd"
if [ -e "$filename" ]; then
	while read -r line; do
		echo "$line" | cut -d ':' -f 1,3,6
	done < $filename
else
	exit
fi
