#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd, using the while loop + IFS

filename="/etc/passwd"
if [ -e "$filename" ]; then
	while IFS=':' read -r username password user_id group_id uid_info home_dir shell; do
		echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $uid_info"
	done < "$filename"
fi
