#!/usr/bin/env bash
# This script tests if a school file exists

file="school"

#check if file exists or not
if [ ! -e $file ]; then
	echo "school file does not exist"
else
	echo "school file exists"

	#check if file is empty or not
	if [ ! -s $file ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	#check if file is a directory or not
	if [ -f $file ]; then
		echo "school file is a regular file"
	fi
fi
